# Generated by Django 2.2.16 on 2021-09-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('start_date', models.DateField(help_text='DD.MM.YYYY', verbose_name='Дата начала')),
                ('start_time', models.TimeField(help_text='HH:MM', verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, help_text='HH:MM', null=True, verbose_name='Время окончания')),
                ('responsible', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('start_date', 'start_time'), name='unique_start_date_time'),
        ),
    ]
